### ISSUE TITLE
composer install error: "Your configuration does not allow connections to..."

### ISSUE THREAD

**Issue by duhaime** [BGSU-LITS/omeka-plugin-CentralAuth#10]
Running `composer install` on a fresh Ubuntu 14.04 AWS instance with default security groups yields the following response:

```
  [Composer\Downloader\TransportException]
  Your configuration does not allow connections to http://pear.php.net/get/XML_Util-1.3.0.tgz. See https://getcomposer.org/doc/06-config.md#se
  cure-http for details.
```

This is because the assets are being requested over http rather than https (which all required assets support). I'll submit a pr to fix this.

**Comment by kloor** [comment]
Thanks for the PR.

**Comment by duhaime** [comment]
Sure thing! Thanks for this library--it's working nicely :)
