### ISSUE TITLE
Improve LDAP Error Reporting

### ISSUE THREAD

**Issue by kloor** [BGSU-LITS/omeka-plugin-CentralAuth#2]
Errors from LDAP should be logged. Currently, they are only displayed when LDAP is the only required auth method, which is less than ideal.

**Comment by gauburtin** [comment]
@kloor klmoor

here are the config options. Omeka login and ldap uid are the same. 

## Options

727 central_auth_ldap   optional
728 central_auth_ldap_host  ldaphost.inha.fr
729 central_auth_ldap_port  389
730 central_auth_ldap_useStartTls  
731 central_auth_ldap_useSsl  
732 central_auth_ldap_username  cn=binduser,ou=softwareaccounts,dc=inha,dc=fr
733 central_auth_ldap_password  bindpwd
734 central_auth_ldap_bindRequiresDn    1
735 central_auth_ldap_baseDn    ou=people,dc=inha,dc=fr
736 central_auth_ldap_accountCanonicalForm  2
737 central_auth_ldap_accountDomainName inha.fr
738 central_auth_ldap_accountDomainNameShort    inha.fr
739 central_auth_ldap_accountFilterFormat

**Comment by kloor** [comment]
We don't use bindRequiresDn, so I'm not too familiar with the options related to that feature. I don't see any reason why they would work differently from the LDAP plugin, but there could be something I'm missing. Both plugins use the Zend_Auth_Adapter_Ldap, which is documented here:
http://framework.zend.com/manual/1.12/en/zend.auth.adapter.ldap.html

One difference between plugins is that the LDAP plugin would match to an Omeka account via the LDAP username being the same as the Omeka username. The CentralAuth plugin instead creates an email address of the LDAP username at the accountDomainName and matches that against the email address for the user in Omeka. So, if somebody logged in as `user`, it would look for their account with the email address `user@inha.fr`.

**Comment by lfarrell** [comment]
Would that be an issue then if your email is user@email.unc.edu, but your site was something like omeka.lib.unc.edu?

Thanks

**Comment by lfarrell** [comment]
From my above comment, it does cause a problem, per issue #3.  I'll try to work on a patch.

**Comment by gauburtin** [comment]
@kloor Thnak you kloor, it works fine for me now with a Omeka user 'user' (same as ldap) whith email user@inha.fr (which will work as fine as user.name@inha.fr)
Option bindRequiresDn = 1 is not a problem
I'd like to let you know that : 
- we use user.name@domain.fr as user email syntax (should be an option in central auth ?)
- we use Shibboleth SSO instead of CAS, as all french universities involved in Renater consortium.
  Best regards,

Gautier

**Comment by kloor** [comment]
@gauburtin, thanks for your feedback!

My current plan is to add separate configuration for how users who log in through CAS or LDAP should be matched with Omeka user records. I plan on offering two options, the first allowing for a username to username match, and the second matching the login username combined with a separately configurable domain name matching the Omeka email address.

Currently, I do not intend to implement Shibboleth as part of the plugin myself. I did attempt to leave room within the plugin for Shibboleth to be added as another SSO option, and I would gladly accept any contributions of an implementation. There was a developer that mentioned in a comment on the LDAP plugin that they were also looking to implement Shibboleth: https://github.com/BGSU-LITS/LDAP-Plugin/issues/5#issuecomment-68451310

**Comment by kloor** [comment]
@gauburtin, I've just pushed an update that now has a new option to choose between matching the Omeka user database via username or email, and add a standard field for email domain that both the CAS and LDAP authentication uses.

I still plan on improving the LDAP error reporting before I package a new release, but feel free to give the changes a try and let me know if there was anything I overlooked.

**Comment by kloor** [comment]
The plugin will now send the error messages from LDAP authentication to Omeka's error log, regardless if LDAP is required or optional. Only the first part of the error message, which is intended to be displayed to the user, is displayed to the user.
