### ISSUE TITLE
Account Domain Name not the same as email domain resulting in login failures

### ISSUE THREAD

**Issue by lfarrell** [BGSU-LITS/omeka-plugin-CentralAuth#3]
@kloor I was trying to troubleshoot our install of CentralAuth.  It looks like this code in the LdapAdapter.php is the culprit on line 32:

$email = $this->getUsername(). '@'.
                $this->_options['ldap']['accountDomainName']

Our ldap account domain is different from our email domain, so logins always fail. If, for example, I hard code our email domain, email.unc.edu, then logins proceed correctly.

Perhaps an option can be added in the config form to add email domain if it's different.

thanks,

Dean

**Comment by kloor** [comment]
Yes, that was a faulty assumption on my part. There should be a separate configuration option for the domain part added to the username obtained from LDAP, like there is for CAS.

**Comment by kloor** [comment]
This is now fixed with a separate option for email domain in v1.2.
