### ISSUE TITLE
SimpleCAS does not allow for a blank URI, causing a double slash after hostname.

### ISSUE THREAD

**Issue by ostertoaster** [BGSU-LITS/omeka-plugin-CentralAuth#5]
For our cas instance, we do not use the format of example.host.edu/cas for our instance. Our CAS service lives at the root of the host.

It appears that the code assumes some form of URI, so our login URL is getting constructed as:

https://example.host.edu//login[etc.]

Note the double slash after the hostname.

Ideally, if URI were empty, the code that builds the string would only include a single slash. As it stands, or CAS login form's POST action is to "//login..." and the post action will not actually work.

Any pointers to where in the code we could make this change would be greatly appreciated. We are happy to make the change and submit our patch if pointed in the right direction.

**Comment by ostertoaster** [comment]
Never mind - found that it's the code that composer grabs from the SimpleCAS plugin.

**Comment by kloor** [comment]
A possible workaround would be to use a single dot character (.) for the URI. For some servers https://example.edu/./login would be interpreted as https://example.edu/login.

Let me know if you report the issue to the SimpleCAS project. If they fix it, I'll package a new version. If they don't, I'd be willing to use a fork the project to fix the issue.

**Comment by ostertoaster** [comment]
Thank you! Submitted pull request to SimpleCAS repo:
https://github.com/saltybeagle/SimpleCAS/pull/13

**Comment by ostertoaster** [comment]
Looks like it has been merged:
https://github.com/saltybeagle/SimpleCAS/commit/15c5b0f7dcaec5bf206b445d80f71192684b26ee

Thanks!
