### ISSUE TITLE
Auto-Provisioning

### ISSUE THREAD

**Issue by kalipekona** [BGSU-LITS/omeka-plugin-CentralAuth#7]
I've set this plugin up to use LDAP for authentication.  My understanding of this plugin is that in order to use LDAP, the user must be added to Omeka first.  Once this is done, that user will receive a confirmation email.  That user must then click on the link in the confirmation email which then asks them to set up a password.  Once the password is set up, the user can then access Omeka, however they must use their active directory password and not the password they just set up.

Similar plugins I have used for other applications allow auto-privisioning of the user ids.  My question is, can this plugin be configured so that the setting up the user ahead of time and confirmation email are not required?  This would allow the end user to simply enter their active directory Id and password in Omeka which would then automatically create the Id in Omeka if it doesn't already exist.  Any information you would provide would be greatly helpful, thanks ahead of time for you assistance.

Clif

**Comment by kloor** [comment]
A feature of the plugin is a checkbox on the new user form that allows you to set the user as active. If that checkbox is checked, they won't be sent the confirmation email and won't have to establish a password.

There are currently no features to auto-provision a user account. I think it would be possible to add that feature and I'd gladly accept a pull request, but I don't think I'll get to it soon. I would look at adding the code to create the account about here: [adapters/LdapAdapter.php#L58](https://github.com/BGSU-LITS/omeka-plugin-CentralAuth/blob/6e5131283cb2f59d5fc2362c2f3de23e8ac0b34f/adapters/LdapAdapter.php#L58)

The current action that adds a user is listed here: [controllers/UsersController.php#L28](https://github.com/BGSU-LITS/omeka-plugin-CentralAuth/blob/6e5131283cb2f59d5fc2362c2f3de23e8ac0b34f/controllers/UsersController.php#L28)

**Comment by kalipekona** [comment]
Thanks Kloor, this is very helpful!
