### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by kanarb** [BGSU-LITS/omeka-plugin-CentralAuth#8]
Hello --

Though I have successfully installed this plugin in the past, I'm now getting an error message and a white screen after installation. I tried reinstalling and am still getting the error. I'm wondering if you have any idea what could be causing this. Thanks.

Error:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /var/www/html/omeka/application/libraries/Zend/Ldap.php on line 151

**Comment by kloor** [comment]
Unfortunately, this is going to be a hard problem to track down. The plugin may not be using an unreasonable amount of memory, but some other code may have already nearly exhausted the memory limit before the plugin requested that 130Kb. It would of just been the straw that broke the camel's back. 

Your memory limit seems sufficiently large. Does your Omeka installation use any other plugins? Are you using a custom theme? You may want to try disabling those to see if it resolves the problem. If so, then try adding them back one-by-one to track down which may be causing the problem. 

You could also try reporting memory_get_usage(true) from some of the PHP code to try narrowing down where memory usage is excessively growing.

**Comment by kloor** [comment]
Closing older issues that did not receive any follow-up.
