### ISSUE TITLE
Zend Ldap_Exception

### ISSUE THREAD

**Issue by hklish01** [BGSU-LITS/omeka-plugin-CentralAuth#9]
Can the CentralAuth plugin for LDAP authentication be used with Omeka 2.4.1?

Once I enter in all the configuration and try to use it to log in, I get the error below.  I already tried changing plugin.ini to set omeka_minimum_version to 2.4.1.

Zend_Ldap_Exception
0x7002: LDAP extension not loaded

exception 'Zend_Ldap_Exception' with message '0x7002: LDAP extension not loaded' in 
.../omeka/application/libraries/Zend/Ldap.php:129
Stack trace:
#0 .../omeka/application/libraries/Zend/Auth/Adapter/Ldap.php(202): Zend_Ldap->__construct()
#1 .../omeka/application/libraries/Zend/Auth/Adapter/Ldap.php(272): Zend_Auth_Adapter_Ldap-

> getLdap()
> # 2 .../omeka/plugins/CentralAuth/adapters/LdapAdapter.php(28): Zend_Auth_Adapter_Ldap-
> 
> authenticate()
> # 3 .../omeka/plugins/CentralAuth/CentralAuthPlugin.php(236): CentralAuth_LdapAdapter-
> 
> authenticate()
> # 4 [internal function]: CentralAuthPlugin->filterLoginAdapter(Object
> 
> (Omeka_Auth_Adapter_UserTable), Array)
> # 5 .../omeka/application/libraries/Omeka/Plugin/Broker.php(271): call_user_func(Array, Object
> 
> (Omeka_Auth_Adapter_UserTable), Array)
> # 6 .../omeka/application/libraries/globals.php(324): Omeka_Plugin_Broker->applyFilters
> 
> ('login_adapter', Object(Omeka_Auth_Adapter_UserTable), Array)
> # 7 .../omeka/application/controllers/UsersController.php(434): apply_filters('login_adapter',
> 
> Object(Omeka_Auth_Adapter_UserTable), Array)
> # 8 .../omeka/plugins/CentralAuth/controllers/UsersController.php(171): UsersController-
> 
> loginAction()
> # 9 .../omeka/application/libraries/Zend/Controller/Action.php(516): CentralAuth_UsersController-
> 
> loginAction()
> # 10 .../omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308):
> 
> Zend_Controller_Action->dispatch('loginAction')
> # 11 .../omeka/application/libraries/Zend/Controller/Front.php(954):
> 
> Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object
> (Zend_Controller_Response_Http))
> # 12 .../omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105):
> 
> Zend_Controller_Front->dispatch()
> # 13 .../omeka/application/libraries/Zend/Application.php(384):
> 
> Zend_Application_Bootstrap_Bootstrap->run()
> # 14 .../omeka/application/libraries/Omeka/Application.php(79): Zend_Application->run()
> # 15 .../omeka/admin/index.php(28): Omeka_Application->run()
> # 16 {main}

**Comment by kloor** [comment]
The error is likely because your PHP installation is not loading the LDAP extension. You can check the output from [phpinfo()](http://php.net/manual/en/function.phpinfo.php) to find out for sure. Look to see that "LDAP Support" is enabled.

If it isn't enabled, you'll need to figure out how to load the extension on your system. Doing so is handled differently depending on how you installed PHP and which OS you are using. Here is the section of the PHP manual about LDAP: http://php.net/ldap

**Comment by hklish01** [comment]
Thanks for responding so quickly.  I'll look into this on our server.

**Comment by pedrojsaba** [comment]
> The error is likely because your PHP installation is not loading the LDAP extension. You can check the output from [phpinfo()](http://php.net/manual/en/function.phpinfo.php) to find out for sure. Look to see that "LDAP Support" is enabled.
> 
> If it isn't enabled, you'll need to figure out how to load the extension on your system. Doing so is handled differently depending on how you installed PHP and which OS you are using. Here is the section of the PHP manual about LDAP: http://php.net/ldap

**Comment by pedrojsaba** [comment]
I'm using the Omeka 2.8 version and CentralAuth 1.5 version. What's the version right php-ldap?

**Comment by kloor** [comment]
@pedrojsaba The LDAP extension should be available from the same source as your PHP installation. For example, if you installed PHP from a package manager like APT, the LDAP extension should be available from the same source in a matching version.

If you are getting an error message that "LDAP extension not loaded", this is most likely your issue. If you are receiving some other error message, please open a separate issue to describe the problem.

**Comment by pedrojsaba** [comment]
I've this problem.
![image](https://user-images.githubusercontent.com/1163827/131536817-eaae4942-0bbf-4f3e-bf56-072b6f49864f.png)

**Comment by kloor** [comment]
@pedrojsaba Yes, it appears that you do not have the PHP LDAP extension installed. Without knowing what operating system or package manager you used to install PHP, I can't provide much more guidance. If you have a server administrator, I suggest asking them if they can install the PHP LDAP extension.

**Comment by pedrojsaba** [comment]
I enabled ldap in php.ini and I installed the php-ldap in Debian 9.5 SO.

Any suggestions?

Pedro J.

**Comment by kloor** [comment]
At the bottom right of the Omeka admin there should be a link that says something like "System Information". That page should display which PHP Extensions are loaded. If you do not see `ldap` in the list, the extension is still not loaded correctly. It may mean you need to restart your server, or that you may have edited a different php.ini file. If you do see it listed, we'll need to investigate further as the error you are receiving is only thrown if PHP can not find the LDAP extension.

**Comment by kloor** [comment]
Closing older issues that did not receive any follow-up.
